name: "Release dev container features & Generate Documentation"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    steps:
      - name: Temp
        run: |
          echo Hello world.
